export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header className="bg-sky-400 p-4">
          <p>Header</p>
        </header>
          {children}
          <footer className="bg-slate-300 p-4">
          <p>Footer</p>
        </footer>
      </body>
      
    </html>
  )
}
