import { Metadata } from "next"
export const metadata: Metadata = {
  // title: 'Next.js',
  title: {
    // absolute: "", // this completely ignores title.template set in the parent
    default: "Next.js Tuorial - codeVoution", // a fall back title for cild route segent
    template: "%s | Codevolution" // to create dnami tittl by adding a prefex or surfix
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header className="bg-sky-400 p-4">
          <p>Header</p>
        </header>
          {children}
          <footer className="bg-slate-300 p-4">
          <p>Footer</p>
        </footer>
      </body>
      
    </html>
  )
}
